data:
  dataset_path: '~/big_data/dataset/nlp/relation-extraction/'
  processed_path: '~/big_data/processed-data/nlp/relation-extraction/pcnn-att/'

  train_data: 'train.txt'

  vocab_file: 'vocab.txt'
  tag_file: 'tag.txt'
  rel_file: 'rel.txt'
  entity_file: 'entity.txt'
  wordvec_file: 'wordvec.txt'
  wordvec_pkl: 'wordvec.pkl'

model:
  class_num: 12
  cnn_filters: 230
  dropout_keep_prob: 0.5
  position_embedding_size: 5
  word_embedding_size: 100

train:
  piece_pooling: 1
  batch_size: 160
  initial_lr: 0.01
  max_steps: 16000

  model_dir: '~/big_data/logs/nlp/relation-extraction/pcnn-att/'
  save_checkpoints_steps: 2000
