data:
  dataset_path: '~/big_data/dataset/nlp/semantic-role-labeling/'
  processed_path: '~/big_data/processed-data/nlp/semantic-role-labeling/bilstm-highway/'

  train_data: 'train.txt'
  test_data: 'test.txt'

  vocab_file: 'vocab.txt'
  tag_file: 'tag.txt'
  label_file: 'label.txt'
  wordvec_file: 'wordvec.txt'
  wordvec_pkl: 'wordvec.pkl'

model:
  num_lstm_layer: 4
  class_num: 78
  tag_num: 33
  lstm_unit: 300

  recurrent_keep_prob: 0.9
  softmax_keep_prob: 0.5

  word_embedding_size: 300
  tag_embedding_size: 50
  predicate_size: 3

train:
  batch_size: 50
  clip_gradients: 1.0

  epoch: 0
  max_epoch: 40

  model_dir: '~/big_data/logs/nlp/semantic-role-labeling/bilstm-highway/'
  save_checkpoints_steps: 2000