data:
  dataset_path: '~/big_data/dataset/nlp/relation-extraction/'
  processed_path: '~/big_data/processed-data/nlp/relation-extraction/bigru-adv-soft_label/'

  train_data: 'train.txt'

  vocab_file: 'vocab.txt'
  tag_file: 'tag.txt'
  rel_file: 'rel.txt'
  entity_file: 'entity.txt'
  wordvec_file: 'wordvec.txt'
  wordvec_pkl: 'wordvec.pkl'

model:
  class_num: 12
  gru_units: 200
  dropout_keep_prob: 0.5
  epsilon: 0.02
  entity_indicator_size: 3
  word_embedding_size: 100

train:
  adversarial_training: 1
  soft_label: 1
  soft_label_start: 3000
  batch_size: 50
  initial_lr: 0.001
  max_steps: 12000

  model_dir: '~/big_data/logs/nlp/relation-extraction/bigru-adv-soft_label/'
  save_checkpoints_steps: 2000